about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('organization/', views.organization_view, name='organization'),
    path('organization/update/', views.organization_update_view, name='organization_update'),
    path('organization/add/', views.organization_add_view, name='organization_add'),
    path('organization/delete/', views.organization_delete_view, name='organization_delete'),
    path('organization/save/', views.organization_save_view, name='organization_save'),
    path('circles/', views.circles_view, name='circles'),
    path('circles/<int:pk>/', views.circles_update_view, name='circles_update'),
    path('labs/', views.labs_view, name='labs'),
    path('labs/<int:pk>/', views.labs_update_view, name='labs_update'),
]

cs_web/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import index

urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('notice/', include('notice.urls')),
    path('free/', include('free.urls')),
    path('anonymous/', include('anonymous.urls')),
    path('about/', include('about.urls')),
    path('calender/', include('calender.urls')),
    path('timetable/', include('timetable.urls')),
]

free/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from django.contrib import messages
from django.shortcuts import redirect


app_name = 'free'

def protected_file(request, path, document_root=None):
    messages.error(request, "접근 불가")
    return redirect('/')

urlpatterns = [
    path('', views.AllListView.as_view(), name='all_list'),
    path('free/', views.FreeListView.as_view(), name='free_list'),
    path('question/', views.QuestionListView.as_view(), name='question_list'),
    path('information/', views.InformationListView.as_view(), name='information_list'),

    path('write/', views.free_write_view, name='free_write'),
    path('<int:pk>/', views.free_detail_view, name='free_detail'),
    path('<int:pk>/edit/', views.free_edit_view, name='free_edit'),
    path('<int:pk>/delete/', views.free_delete_view, name='free_delete'),
    path('download/<int:pk>', views.free_download_view, name="free_download"),

    path('<int:pk>/comment/write/', views.comment_write_view, name='comment_write'),
    path('<int:pk>/comment/delete/', views.comment_delete_view, name='comment_delete'),
]

urlpatterns += static(settings.MEDIA_URL, protected_file, document_root=settings.MEDIA_ROOT)

about/models.py
from django.db import models
from users.choice import RANK_CHOICES, PART_CHOICES


class Organization(models.Model):
    name = models.CharField(max_length=8, verbose_name="이름")
    part = models.CharField(choices=PART_CHOICES, max_length=10, verbose_name='부서')
    rank = models.CharField(choices=RANK_CHOICES, max_length=10, verbose_name='직급')
    registered_date = models.DateTimeField(auto_now_add=True, verbose_name='등록시간')

    def __str__(self):
        return self.name

    class Meta:
        db_table = '학생회조직도'
        verbose_name = '학생회조직도'
        verbose_name_plural = '학생회조직도'


class Circles(models.Model):
    circles_name = models.CharField(max_length=8, verbose_name="동아리이름")
    introduce = models.TextField(verbose_name='동아리소개')
    registered_date = models.DateTimeField(auto_now_add=True, verbose_name='등록시간')

    def __str__(self):
        return self.circles_name

    class Meta:
        db_table = '동아리소개'
        verbose_name = '동아리소개'
        verbose_name_plural = '동아리소개'


class Labs(models.Model):
    labs_name = models.CharField(max_length=8, verbose_name="연구실이름")
    location = models.CharField(max_length=16, verbose_name='연구실위치')
    introduce = models.TextField(verbose_name='연구실소개')
    registered_date = models.DateTimeField(auto_now_add=True, verbose_name='등록시간')

    def __str__(self):
        return self.labs_name

    class Meta:
        db_table = '연구실소개'
        verbose_name = '연구실소개'
        verbose_name_plural = '연구실소개'

about/forms.py
from django import forms
from .models import Organization, Circles, Labs


class OrganizationAddForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(OrganizationAddForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = '이름'
        self.fields['name'].widget.attrs.update({
            'placeholder': '이름',
            'class': 'form-control',
        })
        self.fields['part'].label = '부서'
        self.fields['part'].widget.attrs.update({
            'placeholder': '부서',
            'class': 'form-control',
        })
        self.fields['rank'].label = '직위'
        self.fields['rank'].widget.attrs.update({
            'placeholder': '직위',
            'class': 'form-control',
        })

    class Meta:
        model = Organization
        fields = ['name', 'part', 'rank']


class CirclesEditForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CirclesEditForm, self).__init__(*args, **kwargs)
        # self.fields['circles_name'].label = '동아리이름'
        # self.fields['circles_name'].widget.attrs.update({
        #     'placeholder': '동아리이름',
        #     'class': 'form-control',
        # })
        self.fields['introduce'].label = '동아리소개'
        self.fields['introduce'].widget.attrs.update({
            'placeholder': '동아리소개를 작성해주세요',
            'class': 'md-textarea form-control circlesIntroduce',
            'autofocus': 'autofocus',
        })

    class Meta:
        model = Circles
        fields = ['introduce',]


class LabsEditForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(LabsEditForm, self).__init__(*args, **kwargs)
        self.fields['location'].label = '연구실위치'
        self.fields['location'].widget.attrs.update({
            'placeholder': '연구실위치',
            'class': 'form-control',
        })
        self.fields['introduce'].label = '연구실소개'
        self.fields['introduce'].widget.attrs.update({
            'placeholder': '연구실소개를 작성해주세요',
            'class': 'md-textarea form-control circlesIntroduce',
            'autofocus': 'autofocus',
        })

    class Meta:
        model = Labs
        fields = ['location', 'introduce',]

about/views.py
from django.shortcuts import render, redirect
from users.decorators import login_message_required, admin_required
from .models import Organization, Circles, Labs
from .forms import OrganizationAddForm, CirclesEditForm, LabsEditForm
import json
from django.core import serializers
from django.core.serializers.json import DjangoJSONEncoder
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib import messages


# 학생회 조직도 보기
def organization_view(request):
    organization_list = Organization.objects.all().order_by('rank')
    context = {
        'organization_list': organization_list,
    }
    return render(request, 'about/organization_list.html', context)


# 학생회 조직도 편집모드
@login_message_required
@admin_required
def organization_update_view(request):
    organization_list = Organization.objects.all().order_by('rank')
    context = {
        'organization_list': organization_list,
    }
    return render(request, 'about/organization_update.html', context)


# 학생회 조직도 추가 AJAX
@admin_required
def organization_add_view(request):
    form = OrganizationAddForm()
    context = {
        'list': form,
    }
    return render(request, 'about/organization_add_form.html', context)


# 학생회 조직도 삭제 AJAX
@admin_required
def organization_delete_view(request):
    pk = request.POST.get('id')
    organization_list = Organization.objects.filter(pk=pk)
    organization_list.delete()
    context = {
        'response': 'success',
    }    
    return HttpResponse(json.dumps(context, cls=DjangoJSONEncoder), content_type = "application/json")


# 학생회 조직도 저장
@admin_required
def organization_save_view(request):
    if request.method == "POST":
        form = OrganizationAddForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('about:organization_update')


# 동아리 소개 보기
def circles_view(request):
    circles_list = Circles.objects.all()
    context = {
        'circles_list': circles_list,
    }
    return render(request, 'about/circles_list.html', context)


# 동아리 소개 수정
@login_message_required
@admin_required
def circles_update_view(request, pk):
    circles = Circles.objects.get(id=pk)
    if request.method == "POST":
        form = CirclesEditForm(request.POST, instance=circles)
        if form.is_valid():
            form.save()
            messages.success(request, "수정되었습니다.")
        return redirect('/about/circles/')
    else:
        circles = Circles.objects.get(id=pk)
        circles_name = circles.circles_name
        form = CirclesEditForm(instance=circles)
        context = {
            'form': form,
            'circles_name': circles_name,
        }   
        return render(request, "about/circles_update.html", context)


# 연구실 소개 보기
def labs_view(request):
    labs_list = Labs.objects.all()
    context = {
        'labs_list': labs_list,
    }
    return render(request, 'about/labs_list.html', context)


# 연구실 소개 수정
@login_message_required
@admin_required
def labs_update_view(request, pk):
    labs = Labs.objects.get(id=pk)
    if request.method == "POST":
        form = LabsEditForm(request.POST, instance=labs)
        if form.is_valid():
            form.save()
            messages.success(request, "수정되었습니다.")
        return redirect('/about/labs/')
    else:
        labs = Labs.objects.get(id=pk)
        labs_name = labs.labs_name
        form = LabsEditForm(instance=labs)
        context = {
            'form': form,
            'labs_name': labs_name,
        }   
        return render(request, "about/labs_update.html", context)

templates/about/circles_list.html
{% extends "users/main_base.html" %}
{% load static %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/about/about.css' %}" type="text/css">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row mt-5">
        <div class="col-10">
            <h4 style="font-weight: bold;">컴퓨터공학과 학술동아리</h4>
        </div>
    </div>
</div>
<hr style="width:69rem;">
<br>

{% for list in circles_list %}
    <div class="row justify-content-center">
        <div class="card" style="width: 1100px;">
            <div class="card-header circlesTitle">
                <strong style="font-size: 18px;">{{ list.circles_name }}</strong>
                {% if request.user.level == '0' or request.user.level == '1' %}
                <div style="float: right;">
                    <a class="aboutEditBtn" href="{% url 'about:circles_update' list.id %}">* 편집하기</a>
                </div>
                {% endif %}
            </div>
            <div class="card-body">
                <div>
                    {{ list.introduce|linebreaksbr }}
                </div>
            </div>
        </div>
    </div>
    <br><br>
{% endfor %}
{% endblock %}

templates/about/circles_update.html
{% extends "users/main_base.html" %}
{% load static %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/about/about.css' %}" type="text/css">
{% endblock %}

{% block contents %}
<div class="container">
    <br><br><br>
    <div class="row-mt-5">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="card" style="width: 100%;">
                <div class="card-header circlesTitle">
                    <strong style="font-size: 18px;">{{ circles_name }}</strong>
                </div>
                <div class="card-body">
                    <div class="md-form">
                        <div class="col-sm-12" style="margin-left:-12px;">
                            {{ form.introduce }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="text-right" style="margin-top: 10px;">
                <a onclick="location.href='/about/circles/'" class="btn btn-sm" id="back_btn"><i class="fa fa-reply"></i>&nbsp;돌아가기</a>
                <button type="submit" id="write" class="btn btn-sm"><i class="fas fa-check"></i>&nbsp;수정하기</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

templates/about/labs_list.html
{% extends "users/main_base.html" %}
{% load static %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/about/about.css' %}" type="text/css">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row mt-5">
        <div class="col-10">
            <h4 style="font-weight: bold;">컴퓨터공학과 연구실</h4>
        </div>
    </div>
</div>
<hr style="width:69rem;">
<br>

{% for list in labs_list %}
    <div class="row justify-content-center">
        <div class="card" style="width: 1100px;">
            <div class="card-header circlesTitle">
                <strong style="font-size: 18px;">{{ list.labs_name }}</strong>
                {% if request.user.level == '0' or request.user.level == '1' %}
                <div style="float: right;">
                    <a class="aboutEditBtn" href="{% url 'about:labs_update' list.id %}">* 편집하기</a>
                </div>
                {% endif %}
            </div>
            <div class="card-body">
                <div>
                    <div class="labLocation">
                        <i class="fas fa-map-marker-alt"></i>&nbsp;{{ list.location }}
                    </div>
                    {{ list.introduce|linebreaksbr }}
                </div>
            </div>
        </div>
    </div>
    <br><br>
{% endfor %}
{% endblock %}

templates/about/labs_update.html
{% extends "users/main_base.html" %}
{% load static %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/about/about.css' %}" type="text/css">
{% endblock %}

{% block contents %}
<div class="container">
    <br><br><br>
    <div class="row-mt-5">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="card" style="width: 100%;">
                <div class="card-header circlesTitle">
                    <strong style="font-size: 18px;">{{ labs_name }}</strong>
                </div>
                <div class="card-body">
                    {{ form.location }}
                    <div class="md-form">
                        <div class="col-sm-12" style="margin-left:-12px;">
                            {{ form.introduce }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="text-right" style="margin-top: 10px;">
                <a onclick="location.href='/about/labs/'" class="btn btn-sm" id="back_btn"><i class="fa fa-reply"></i>&nbsp;돌아가기</a>
                <button type="submit" id="write" class="btn btn-sm"><i class="fas fa-check"></i>&nbsp;수정하기</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

templates/about/organization_add_form.html
<td class="tdClass add_td">{{ list.part }}</td>
<td class="tdClass">{{ list.rank }}</td>
<td class="tdClass">{{ list.name }}</td>
<td class="borderNone"><button class="btn btn-sm" id="organizationSaveBtn" type="submit">저장</a></td>

templates/about/organization_list.html
{% extends "users/main_base.html" %}
{% load static %}

{% block mobileView %}
<meta name="viewport" content="width=1200, user-scalable=yes">
{% endblock %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/about/about.css' %}" type="text/css"> 
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row mt-5">
        <div class="col-10">
            <h4 style="font-weight: bold;">컴퓨터공학과 학생회 조직도</h4>
        </div>
        {% if request.user.level == '0' or request.user.level == '1' %}
        <a class="organizationEditBtn" href="{% url 'about:organization_update' %}">* 편집하기</a>
        {% endif %}
    </div>
</div>
<hr style="width:69rem;">
<br><br>
<div class="row justify-content-md-center">
    <div class="card organizationCard">
        <div class="row justify-content-md-center">
            <div class="card organizationCardTitle">
                <h5 class="organizationTitle">학생회</h5>
            </div>
        </div>
        <div class="card-body organizationBody">
            {% for list in organization_list %}
                {% if list.rank == '1' %}
                    <span class="oragnizationRank">회장</span>
                    <span class="oragnizationName">{{ list.name }}</span><br>
                {% elif list.rank == '2' %}
                    <span class="oragnizationRank">부회장</span>
                    <span class="oragnizationName">{{ list.name }}</span><br>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
<br><br><br>
<div class="row justify-content-md-center">
    <div class="card organizationChild">
        <div class="row justify-content-md-center">
            <div class="card organizationCardTitle">
                <h5 class="organizationTitle">복지부</h5>
            </div>
        </div>
        <div class="card-body organizationBody">
            {% for list in organization_list %}
                {% if list.part == '복지부' %}
                    {% if list.rank == '3' %}
                        <span class="oragnizationRank">부장</span>
                        <span class="oragnizationName">{{ list.name }}</span><br>
                    {% elif list.rank == '4' %}
                        <span class="oragnizationRank">차장</span>
                        <span class="oragnizationName">{{ list.name }}</span><br>
                    {% elif list.rank == '5' %}
                        <span class="oragnizationRank">부원</span>
                        <span class="oragnizationName">{{ list.name }}</span><br>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </div>
    </div>
    <div class="card organizationChild">
        <div class="row justify-content-md-center">
            <div class="card organizationCardTitle">
                <h5 class="organizationTitle">총무부</h5>
            </div>
        </div>
        <div class="card-body organizationBody">
            {% for list in organization_list %}
                {% if list.part == '총무부' %}
                    {% if list.rank == '3' %}
                        <span class="oragnizationRank">부장</span>
                        <span class="oragnizationName">{{ list.name }}</span><br>
                    {% elif list.rank == '4' %}
                        <span class="oragnizationRank">차장</span>
                        <span class="oragnizationName">{{ list.name }}</span><br>
                    {% elif list.rank == '부원' %}
                        <span class="oragnizationRank">부원</span>
                        <span class="oragnizationName">{{ list.name }}</span><br>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </div>
    </div>
    <div class="card organizationChild">
        <div class="row justify-content-md-center">
            <div class="card organizationCardTitle">
                <h5 class="organizationTitle">기획부</h5>
            </div>
        </div>
        <div class="card-body organizationBody">
            {% for list in organization_list %}
                {% if list.part == '기획부' %}
                    {% if list.rank == '3' %}
                        <span class="oragnizationRank">부장</span>
                        <span class="oragnizationName">{{ list.name }}</span><br>
                    {% elif list.rank == '4' %}
                        <span class="oragnizationRank">차장</span>
                        <span class="oragnizationName">{{ list.name }}</span><br>
                    {% elif list.rank == '5' %}
                        <span class="oragnizationRank">부원</span>
                        <span class="oragnizationName">{{ list.name }}</span><br>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/about/organization_update.html
{% extends "users/main_base.html" %}
{% load static %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/about/about.css' %}" type="text/css">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <div>
                <h4 style="font-weight: bold; margin-left:60px"><i class="fas fa-cog"></i>&nbsp;학생회 조직도 업데이트 (관리자)</h4>
            </div>
            
            <form method="POST" action="{% url 'about:organization_save' %}">
                {% csrf_token %}
                <table class="table table-sm">
                    <thead>
                        <tr class="text-center">
                            <th class="updatePart" scope="col">부서</th>
                            <th class="updateRank" scope="col">직위</th>
                            <th class="updateName" scope="col">이름</th>
                            <th class="borderNone" scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for list in organization_list %}
                        <tr id="{{ list.id }}">
                            <tr name="origin_list" id="origin_{{ list.id }}" class="text-center">
                                <td class="tdClass">{{ list.part }}</td>
                                {% if list.rank == '1' %}
                                <td class="tdClass">회장</td>
                                {% elif list.rank == '2' %}
                                <td class="tdClass">부회장</td>
                                {% elif list.rank == '3' %}
                                <td class="tdClass">부장</td>
                                {% elif list.rank == '4' %}
                                <td class="tdClass">차장</td>
                                {% elif list.rank == '5' %}
                                <td class="tdClass">부원</td>
                                {% endif %}
                                <td class="tdClass">{{ list.name }}</td>
                                <td class="borderNone"><a class="btn btn-sm organizationDeleteBtn" onclick="OrganizationDelete('{{list.id}}');">삭제</a></td>
                            </tr>
                        </tr>
                        {% endfor %}
                        <tr id="organizationAddTable">
                        </tr>
                    </tbody>
                </table>
                <div style="text-align: center;">
                    <i id="organizationAddIcon" class="fas fa-plus-circle fa-2x"></i>
                </div>  

                <div class="text-right" style="margin-top: -10px;">
                    <a onclick="location.href='/about/organization/'" class="btn btn-sm" id="back_btn"><i class="fa fa-reply"></i>&nbsp;돌아가기</a>
                    <!-- <button type="submit" id="write" class="btn btn-sm"><i class="fas fa-check"></i>&nbsp;저장하기</button> -->
                </div>

            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('#organizationAddIcon').click(function () {
        $.ajax({
            type: "POST",
            url: "{% url 'about:organization_add' %}",
            dataType: "html",
            data: {
                'csrfmiddlewaretoken': '{{csrf_token}}',
            },
            success: function (data) {
                $('#organizationAddTable').html(data);
            },
            error: function () {
                console.log(error);
            },
        })
    });

    function OrganizationDelete(value) {
        var organization_id = value;
        $.ajax({
            type: "POST",
            url: "{% url 'about:organization_delete' %}",
            dataType: "json",
            data: {
                'id':organization_id,
                'csrfmiddlewaretoken': '{{csrf_token}}',
            },
            success: function (response) {
                $('#'+value).remove();
                $('#origin_'+value).remove();
            },
            error: function () {
                console.log(error);
            },
        })
    };

    function DeleteAddArea($targetObj) {
        var isIn = true;
        var $objArr = Array();
        var opts = {
            left: 99999, right: 0, top: 99999, bottom: 0
        }
        if( $targetObj ) {
            if( $targetObj.length == 1 ) {
                $objArr.push( $targetObj );
            } else {
                $objArr = $targetObj;
            }
            $.each($objArr, function(i, $obj) {          
                var obj_position = $obj.offset();
                obj_position.right = parseInt( obj_position.left ) + ( $obj.width() );
                obj_position.bottom = parseInt( obj_position.top ) + parseInt( $obj.height() );
                
                if( obj_position.left < opts.left ) opts.left = obj_position.left;
                if( obj_position.right > opts.right ) opts.right = obj_position.right;
                if( obj_position.top < opts.top ) opts.top = obj_position.top;
                if( obj_position.bottom > opts.bottom ) opts.bottom = obj_position.bottom;
            }); 
            if(( opts.left <= event.pageX && event.pageX <= opts.right )&& ( opts.top <= event.pageY && event.pageY <= opts.bottom )) {
                isIn = false;
            }
        }
        return isIn;
    }
    
    $(function(){
        $(document).mousedown(function(e){
            if( DeleteAddArea ($("#organizationAddTable"))) {
                $(".add_td").closest("tr").empty();
            }
        });
    });
</script>
{% endblock %}