anonymous/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from django.contrib import messages
from django.shortcuts import redirect
from users.decorators import login_message_required
from django.views.static import serve

app_name = 'anonymous'

@login_message_required
def protected_file(request, path, document_root=None):
    return serve(request, path, document_root)

urlpatterns = [
    path('', views.AnonymousListView.as_view(), name='anonymous_list'),
    path('search/', views.anonymous_search_view, name='anonymous_search'),
    path('write/', views.anonymous_write_view, name='anonymous_write'),

    path('<int:pk>/', views.anonymous_detail_view, name='anonymous_detail'),
    path('<int:pk>/edit/', views.anonymous_edit_view, name='anonymous_edit'),
    path('<int:pk>/delete/', views.anonymous_delete_view, name='anonymous_delete'),

    path('<int:pk>/comment/write/', views.comment_write_view, name='comment_write'),
    path('<int:pk>/comment/delete/', views.comment_delete_view, name='comment_delete'),

    path('like/', views.post_like_view, name='post_like'),
]

urlpatterns += static(settings.MEDIA_URL, protected_file, document_root=settings.MEDIA_ROOT)

calender/urls.py
from django.urls import path
from . import views

app_name = 'calendar'

urlpatterns = [
	path('', views.calendar_view, name='calendar'),
	path('alleventsj/', views.allEventsJSON, name='allEventsJSON'),
	path('updateEvent/', views.updateEvent, name='updateEvent'),
	path('viewEvent/', views.viewEvent, name='viewEvent'),
	path('forceDelete/', views.forceDelete, name='forceDelete'),
	path('allEvents/', views.allEvents, name='allEvents'),
]

cs_web/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import index

urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('notice/', include('notice.urls')),
    path('free/', include('free.urls')),
    path('anonymous/', include('anonymous.urls')),
    path('about/', include('about.urls')),
    path('calender/', include('calender.urls')),
    path('timetable/', include('timetable.urls')),
]

free/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from django.contrib import messages
from django.shortcuts import redirect


app_name = 'free'

def protected_file(request, path, document_root=None):
    messages.error(request, "접근 불가")
    return redirect('/')

urlpatterns = [
    path('', views.AllListView.as_view(), name='all_list'),
    path('free/', views.FreeListView.as_view(), name='free_list'),
    path('question/', views.QuestionListView.as_view(), name='question_list'),
    path('information/', views.InformationListView.as_view(), name='information_list'),

    path('write/', views.free_write_view, name='free_write'),
    path('<int:pk>/', views.free_detail_view, name='free_detail'),
    path('<int:pk>/edit/', views.free_edit_view, name='free_edit'),
    path('<int:pk>/delete/', views.free_delete_view, name='free_delete'),
    path('download/<int:pk>', views.free_download_view, name="free_download"),

    path('<int:pk>/comment/write/', views.comment_write_view, name='comment_write'),
    path('<int:pk>/comment/delete/', views.comment_delete_view, name='comment_delete'),
]

urlpatterns += static(settings.MEDIA_URL, protected_file, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from django.contrib import messages
from django.shortcuts import redirect


app_name = 'notice'

def protected_file(request, path, document_root=None):
    messages.error(request, "접근 불가")
    return redirect('/')

urlpatterns = [
    path('', views.NoticeListView.as_view(), name='notice_list'),
    path('write/', views.notice_write_view, name='notice_write'),
    path('<int:pk>/', views.notice_detail_view, name='notice_detail'),
    path('<int:pk>/edit/', views.notice_edit_view, name='notice_edit'),
    path('<int:pk>/delete/', views.notice_delete_view, name='notice_delete'),
    path('download/<int:pk>', views.notice_download_view, name="notice_download"),
]

urlpatterns += static(settings.MEDIA_URL, protected_file, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # path('', views.index),
    # path('login/', views.login_view, name='login'),
    path('main/', views.main_view, name='main'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('recovery/id/', views.RecoveryIdView.as_view(), name='recovery_id'),
    path('recovery/pw/', views.RecoveryPwView.as_view(), name='recovery_pw'),
    path('recovery/id/find/', views.ajax_find_id_view, name='ajax_id'),
    path('recovery/pw/find/', views.ajax_find_pw_view, name='ajax_pw'),
    path('recovery/pw/auth/', views.auth_confirm_view, name='recovery_auth'),
    path('recovery/pw/reset/', views.auth_pw_reset_view, name='recovery_pw_reset'),
    # path('recovery/reset/', views.AuthPwResetView.as_view(), name='recovery_pw_reset'),

    path('agreement/', views.AgreementView.as_view(), name='agreement'),
    # path('register/', views.register_view, name='register'),
    path('register/', views.RegisterView.as_view(), name='register'),
    # path('csregister/', views.cs_register_view, name='csregister'),
    path('csregister/', views.CsRegisterView.as_view(), name='csregister'),
    path('registerauth/', views.register_success, name='register_success'),
    path('activate/<str:uid64>/<str:token>/', views.activate, name='activate'),

    path('profile/', views.profile_view, name='profile'),
    path('profile/post', views.profile_post_view, name='profile_post'),
    path('profile/comment', views.profile_comment_view, name='profile_comment'),
    path('profile/update/', views.profile_update_view, name='profile_update'),
    path('profile/delete/', views.profile_delete_view, name='profile_delete'),
    path('profile/password/', views.password_edit_view, name='password_edit'),
]

free/models.py
import os
from django.conf import settings
from django.db import models
from django.utils import timezone
from datetime import datetime, timedelta
from users.choice import CATEGORY_CHOICES
from uuid import uuid4
from notice.models import get_file_path


class Free(models.Model):
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, verbose_name='작성자')
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=18, verbose_name='분류', default='자유')
    title = models.CharField(max_length=128, verbose_name='제목')
    content = models.TextField(verbose_name='내용')
    hits = models.PositiveIntegerField(verbose_name='조회수', default=0)
    comments = models.PositiveIntegerField(verbose_name='댓글수', null=True)
    files = models.FileField(upload_to=get_file_path, null=True, blank=True, verbose_name='이미지파일') # summernote MultiValueDict : files
    upload_files = models.FileField(upload_to=get_file_path, null=True, blank=True, verbose_name='파일')
    registered_date = models.DateTimeField(auto_now_add=True, verbose_name='등록시간')
    filename = models.CharField(max_length=64, null=True, verbose_name='첨부파일명')

    def __str__(self):
        return self.title

    # def filename(self):
    #     return os.path.basename(self.upload_files.name)

    def delete(self, *args, **kargs):
        if self.upload_files:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.upload_files.path))
        super(Free, self).delete(*args, **kargs)

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.registered_date

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.registered_date.date()
            return str(time.days) + '일 전'
        else:
            return False

    class Meta:
        db_table = '자유게시판'
        verbose_name = '자유게시판'
        verbose_name_plural = '자유게시판'


class Comment(models.Model):
    post = models.ForeignKey(Free, on_delete=models.CASCADE, verbose_name='게시글')
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, verbose_name='댓글작성자')
    # writer = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE, verbose_name='댓글작성자')
    # writer = models.CharField(max_length=17, null=True, verbose_name='댓글작성자')
    content = models.TextField(verbose_name='댓글내용')
    created = models.DateTimeField(auto_now_add=True, verbose_name='작성일')
    deleted = models.BooleanField(default=False, verbose_name='삭제여부')
    reply = models.IntegerField(verbose_name='답글위치', default=0)
    
    def __str__(self):
        return self.content

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.created

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created.date()
            return str(time.days) + '일 전'
        else:
            return False 

    class Meta:
        db_table = '자유게시판 댓글'
        verbose_name = '자유게시판 댓글'
        verbose_name_plural = '자유게시판 댓글'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from .choice import *


class UserManager(BaseUserManager):

    def create_user(self, user_id, password, email, hp, name, student_id, grade, department, circles, auth, **extra_fields):
        if not user_id:
            raise ValueError('user_id Required!')

        user = self.model(
            user_id = user_id,
            email = email,
            hp = hp,
            name = name,
            student_id = student_id,
            grade = grade,
            department = department,
            circles = circles,
            auth = auth,
            **extra_fields
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, user_id, password, email=None, hp=None, name=None, student_id=None, grade=None, department=None, circles=None, auth=None):

        user = self.create_user(user_id, password, email, hp, name, student_id, grade, department, circles, auth)

        user.is_superuser = True
        user.is_staff = True
        user.is_admin = True
        user.level = 0

        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    
    objects = UserManager()

    user_id = models.CharField(max_length=17, verbose_name="아이디", unique=True)
    password = models.CharField(max_length=256, verbose_name="비밀번호")
    email = models.EmailField(max_length=128, verbose_name="이메일",null=True, unique=True)
    hp = models.IntegerField(verbose_name="핸드폰번호", null=True, unique=True)
    name = models.CharField(max_length=8, verbose_name="이름", null=True)
    student_id = models.IntegerField(verbose_name="학번", null=True)
    grade = models.CharField(choices=GRADE_CHOICES, max_length=18, verbose_name="학년", null=True)
    level = models.CharField(choices=LEVEL_CHOICES, max_length=18, verbose_name="등급", default=3)
    circles = models.CharField(choices=CIRCLES_CHOICES, max_length=18, verbose_name="동아리", null=True)
    department = models.CharField(choices=DEPARTMENT_CHOICES, max_length=24, verbose_name="학과", null=True)
    auth = models.CharField(max_length=10, verbose_name="인증번호", null=True)
    date_joined = models.DateTimeField(auto_now_add=True, verbose_name='가입일', null=True, blank=True)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'user_id'
    REQUIRED_FIELDS = ['email']
    
    def __str__(self):
        return self.user_id

    class Meta:
        db_table = "회원목록"
        verbose_name = "사용자"
        verbose_name_plural = "사용자"

templates/users/login.html
{% extends "users/user_base.html" %}
{% load static %}

{% block mobileView %}
<meta name="viewport" content="width=480, user-scalable=yes">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row justify-content-md-center">
        <div style="position: absolute; top: 40%; height: 476.06px; margin-top: -238.03px;">
            <div class="card" style="width: 30rem;">
                <div class="card-body">
                    <div class="text-center">
                        <a href="/"><img src="{% static 'img/logo2.jpg' %}" style="width:60%; margin:30px;"></a>
                    </div>

                    <form method="POST" action="." novalidate>
                        {% csrf_token %}

                        <div class="mb-4 md-form">
                            <label name="label_user_id" for="{{ form.user_id.id_for_label }}"><i class="fas fa-user"></i>&nbsp;&nbsp;{{ form.user_id.label }}</label>
                            {{ form.user_id }}
                            <script type="text/javascript">
                                if (document.getElementsByName('user_id')[0].value != '') {
                                    document.getElementsByName('label_user_id')[0].setAttribute('class', 'active');
                                }
                            </script>
                            {% if form.user_id.errors %}
                            <script type="text/javascript">
                                document.getElementsByName('user_id')[0].setAttribute('class',
                                    'form-control is-invalid')
                            </script>
                            {% for error in form.user_id.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                            {% endfor %}
                            {% endif %}
                        </div>

                        <div class="mb-4 md-form">
                            <label for="{{ form.password.id_for_label }}"><i class="fas fa-lock"></i>&nbsp;&nbsp;{{ form.password.label }}</label>
                            {{ form.password }}

                            {% if form.password.errors %}
                            <script type="text/javascript">
                                document.getElementsByName('password')[0].setAttribute('class', 'form-control is-invalid')
                            </script>
                            {% for error in form.password.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                            {% endfor %}
                            {% endif %}
                        </div>

                        <!-- {{ login_form }} -->
                        <label>
                            <input type="checkbox" name="remember_session"/>
                            <span style="padding-bottom: 35px;">로그인 상태 유지</span>
                        </label>
                        <br>
                        <!-- <input type="checkbox" name="remember_session" > 로그인 상태 유지<br><br> -->

                        <button type="submit" style="opacity: 90%; font-size: 16px; margin-top: -5px;" class="btn btn-blue btn-lg btn-block">로그인</button>
                    </form>
                    <div style="text-align: center;">
                        <a style="color:gray; font-size: 14px;" href="{% url 'users:recovery_id' %}">아이디</a>&nbsp;&middot;
                        <a style="color:gray; font-size: 14px;" href="{% url 'users:recovery_pw' %}">비밀번호찾기</a>&nbsp;&middot;
                        <a style="color:gray; font-size: 14px;" href="{% url 'users:agreement' %}">회원가입</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/users/main.html
{% extends "users/main_base.html" %}
{% load static %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/index/owl.carousel.min.css' %}">
{% endblock %}

{% block contents %}
<div style="margin: 55px -10px -40px 4px;">
    <div class="container" id="carouselContainer" style="margin-bottom: -5px;">
        <div>
            <a href="#" class="customPrevBtn carouselHover" style="float:left;"><i class="fas fa-chevron-circle-left fa-2x"></i></a>
        </div>
        <!-- <div class="container" style="width: 91%; float:left;"> -->
        <div class="container" id="carouselMinBtn" style="width: 91%; float:left; padding: 0 !important">
        <!-- <div class="container" style="width: 83%; float:left;"> -->
            <div class="owl-carousel centernonloop">
                <a href="https://www.sangji.ac.kr/prog/bbsArticle/BBSMSTR_000000000325/list.do" target="_blank" class="item-class">
                    <div class="text" style="text-align: center;">
                        <h5 class="class-heading carouselFont"><i class="fas fa-notes-medical"></i>&nbsp;상지 뉴스</h5>
                    </div>
                </a>
                <a href="https://www.sangji.ac.kr/prog/bbsArticle/BBSMSTR_000000000041/list.do?cmsNoStr=90" target="_blank" class="item-class">
                    <div class="text" style="text-align: center;">
                        <h5 class="class-heading carouselFont"><i class="fas fa-user-check"></i>&nbsp;<span id="injeLink1">상지대 학사공지</span></h5>
                    </div>
                </a>
                <a href="https://www.sangji.ac.kr/prog/bbsArticle/BBSMSTR_000000000042/list.do" target="_blank" class="item-class">
                    <div class="text" style="text-align: center;">
                        <h5 class="class-heading carouselFont"><i class="fas fa-user-graduate"></i>&nbsp;<span id="injeLink2">상지대 장학공지</span></h5>
                    </div>
                </a>
                <a href="https://caam.sangji.ac.kr/main/brd/user_recommend_notice.do" target="_blank" class="item-class">
                    <div class="text" style="text-align: center;">
                        <h5 class="class-heading carouselFont"><i class="fas fa-user-tie"></i>&nbsp;<span id="injeLink3">상지대 취업/모집</span></h5>
                    </div>
                </a>
                <a href="https://www.sangji.ac.kr/kor/sub06_04_04.do" target="_blank" class="item-class">
                    <div class="text" style="text-align: center;">
                        <h5 class="class-heading carouselFont"><i class="fas fa-bed"></i>&nbsp;생활관 홈페이지</h5>
                    </div>
                </a>
                <a href="http://library.sangji.ac.kr/main_main.mir" target="_blank" class="item-class">
                    <div class="text" style="text-align: center;">
                        <h5 class="class-heading carouselFont"><i class="fas fa-book-open"></i>&nbsp;학술정보원</h5>
                    </div>
                </a>
                <a href="https://www.sangji.ac.kr/kor/sub06_04_01_03.do" target="_blank" class="item-class">
                    <div class="text" style="text-align: center;">
                        <h5 class="class-heading carouselFont"><i class="fas fa-bus"></i>&nbsp;통학버스</h5>
                    </div>
                </a>
                <a href="https://www.sangji.ac.kr/prog/carteGuidance/kor/sub07_10_01/DS/calendar.do" target="_blank" class="item-class">
                    <div class="text" style="text-align: center;">
                        <h5 class="class-heading carouselFont"><i class="fas fa-utensils"></i>&nbsp;오늘의 식단보기</h5>
                    </div>
                </a>
            </div>
        </div>
        <div>
            <a href="#" class="customNextBtn carouselHover"><i class="fas fa-chevron-circle-right fa-2x"></i></a>
        </div>
    </div>
    <br>
    <br>
    <div class="row">
        <div class="col-sm-6">
            <!-- <div class="shadow p-3 mb-5 bg-white rounded" style="height: 90%; width:98%;"> -->
            <div class="shadow p-3 mb-5 bg-white rounded" style="width:98%;">
                <span style="font-size: 20px; font-weight: bold; float:left;"><i
                        class="fas fa-bullhorn"></i>&nbsp;&nbsp;최근 공지사항</span>
                <div style="text-align: right; margin-bottom: 50px; padding-top: -5px;">
                    <a href="{% url 'notice:notice_list' %}" style="background-color: #356CCCF5; color:white; font-size: 13px; margin-top: -5px; margin-right: -5px;" class="btn btn btn-sm">전체보기</a>
                </div>

                <div style="margin-bottom: -47.56px;">
                {% for notice in notice_list %}
                <div class="notice_box">
                    <div class="shadow-none mb-5 bg-light rounded" onclick="location.href='/notice/{{ notice.id }}'"
                        style="padding: 12px; margin-top: -36px; margin-bottom: -36px; cursor:pointer; height:52px;">
                        <!-- <span style="color: gray; font-size:16px;"><i class="fas fa-bullhorn"></i>&nbsp;&nbsp;{{ notice.title|truncatechars:30 }}</span> -->
                        <span style="color: gray; font-size:16px; font-weight:550;">&nbsp;&nbsp;{{ notice.title|truncatechars:24 }}</span>
                        <!-- <div style="float:right">
                            <span style="color: gray; font-size:16px">{{ notice.registered_date|date:'Y. m. d' }}</span>
                        </div> -->
                    </div>
                </div>
                {% endfor %}
                </div>
            </div>
        </div>

        <div class="col-sm-6">
            <!-- <div class="shadow p-3 mb-5 bg-white rounded" style="height: 88.9%; width:98%"> -->
            <div class="shadow p-3 mb-5 bg-white rounded" style="width:98%">
                <span style="font-size: 20px; font-weight: bold; float:left;"><i
                        class="fas fa-calendar-check"></i>&nbsp;&nbsp;<span id="mainpageCalenderId">컴퓨터공학과 학사일정</span></span>
                <div style="text-align: right; margin-bottom: 10px;">
                    <a href="{% url 'calendar:calendar' %}" style="background-color: #356CCCF5; color:white; font-size: 13px; margin-top: -5px; margin-right: -5px;" class="btn btn btn-sm">전체보기</a>
                </div>     

                <!-- <div style="margin-bottom: -47.56px"> -->
                <div style="margin-bottom: -9px">
                {% for calendar in calendar_list %}
                <div class="notice_box">
                    <div class="shadow-none mb-5 bg-light rounded" onclick="location.href='/calender/'"
                        style="padding: 12px; margin-top: 0px; margin-bottom: 12px !important; cursor:pointer; height:52px;">
                        {% if calendar.d_day == 'D-DAY' %}
                        <span style="font-weight: bold; color: #0045d1f2">{{ calendar.d_day }}</span>
                        {% else %}
                        <span style="font-weight: bold; color:rgb(88, 88, 88)">{{ calendar.d_day }}</span>
                        {% endif %}
                        <span style="color: gray; font-size:16px; font-weight: 550;">&nbsp;&nbsp;{{ calendar.event_name|truncatechars:11 }}</span>
                        <div style="float:right">
                            <span style="color: gray; font-size:16px">{{ calendar.start_date }}</span>
                        </div>
                    </div>
                </div>
                {% endfor %}
                </div>
            </div>
        </div>

    </div>

    <div class="row">
        <!-- <div class="col-sm-6" style="height: 45vh;"> -->
        <div class="col-sm-6">
            <!-- <div class="shadow p-3 mb-5 bg-white rounded" style="height: 90%; width:98%"> -->
            <div class="shadow p-3 mb-5 bg-white rounded" style="width:98%">
                <span style="font-size: 20px; font-weight: bold; float:left;"><i
                        class="fas fa-info-circle"></i>&nbsp;&nbsp;자유게시판 정보글</span>
                <div style="text-align: right; margin-bottom: 10px;">
                    <a href="{% url 'free:information_list' %}" style="background-color: #356CCCF5; color:white; font-size: 13px; margin-top: -5px; margin-right: -5px;" class="btn btn btn-sm">전체보기</a>
                </div>

                <div style="margin-bottom: -13px;">
                {% for free in free_list %}
                <div class="notice_box">
                    <div class="shadow-none mb-5 bg-light rounded" onclick="location.href='/free/{{ free.id }}/'"
                        style="padding: 12px; margin-top: 0px; margin-bottom: 12px !important; cursor:pointer; height:52px;">
                        <!-- <span style="color: gray; font-size:16px;"><i class="fas fa-splotch"></i>&nbsp;&nbsp;{{ free.title|truncatechars:30 }}</span> -->
                        <span style="color: gray; font-size:16px; font-weight:550;">&nbsp;&nbsp;{{ free.title|truncatechars:24 }}</span>
                        <!-- <div style="float:right">
                            <span style="color: gray; font-size:16px">{{ free.registered_date|date:'Y. m. d' }}</span>
                        </div> -->
                    </div>
                </div>
                {% endfor %}
                </div>

            </div>
        </div>
        <!-- <div class="col-sm-6" style="height: 45vh;"> -->
        <div class="col-sm-6">
            <!-- <div class="shadow p-3 mb-5 bg-white rounded" style="height: 90%; width:98%"> -->
            <div class="shadow p-3 mb-5 bg-white rounded" style="width:98%">
                <!-- <span style="font-size: 20px; font-weight: bold; float:left;"><i class="fas fa-pepper-hot"></i>&nbsp;&nbsp;익명게시판 HOT</span> -->
                <span style="font-size: 20px; font-weight: bold; float:left;"><i class="fas fa-fire-alt"></i>&nbsp;&nbsp;익명게시판 HOT</span>
                <div style="text-align: right; margin-bottom: 10px;">
                    <a href="{% url 'anonymous:anonymous_list' %}" style="background-color: #356CCCF5; color:white; font-size: 13px; margin-top: -5px; margin-right: -5px;" class="btn btn btn-sm">전체보기</a>
                </div>

                <div style="margin-bottom: -13px;">
                {% for anonymous in anonymous_list %}
                <div class="notice_box">
                    <div class="shadow-none mb-5 bg-light rounded" onclick="location.href='/anonymous/{{ anonymous.id }}/'"
                        style="padding: 12px; margin-top: 0px; margin-bottom: 12px !important; cursor:pointer; height:52px;">
                        <!-- <span style="color: gray; font-size:16px;"><i class="fas fa-fire-alt"></i>&nbsp;&nbsp;{{ anonymous.title|truncatechars:30 }}</span> -->
                        <span style="color: gray; font-size:16px; font-weight:550;">&nbsp;&nbsp;{{ anonymous.title|truncatechars:24 }}</span>
                        <div style="float:right">
                            <span style="color: gray; font-size:16px"><i class="fas fa-thumbs-up" style="opacity: 80%;"></i>&nbsp;&nbsp;{{ anonymous.like_count }}&nbsp;&nbsp;<i class="fas fa-comments" style="opacity: 80%;"></i>&nbsp;&nbsp;{{ anonymous.comments }}</span>
                        </div>
                    </div>
                </div>
                {% endfor %}
                </div>

            </div>
        </div>
    </div>
</div>

<script src="{% static 'js/index/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/index/aos.js' %}"></script>
<script src="{% static 'js/index/jquery.sticky.js' %}"></script>
<script src="{% static 'js/index/customCarousel.js' %}"></script>
{% endblock %}

templates/users/register_email.html
{% autoescape off %}
<!DOCTYPE html>
<html>
<body>
    <div style="width:100%;min-width:100%;height:100%;">
        <div style="padding: 70px 0; background: #f7f8f9;">
            <div style="margin: 0 auto; width: 600px; color: #000;">
                <div style="padding: 30px 90px; text-align: center; border: 1px solid #dfdfdf; background: #fff;">
                    <h3 style="margin-bottom: 35px; font-size: 30px; font-weight: 600;">회원가입 이메일 인증 발송</h3>
                    <div style="padding: 10px 0 20px; border-top: 1px solid rgb(172, 172, 172);">
                        <p style="font-size: 14px; font-weight: 600; line-height: 20px;">상지대학교 Sangji_Computer 홈페이지 회원가입을 축하드립니다.<br>아래 링크를 클릭하여 로그인 해주시기 바랍니다.</p>
                    </div>
                    <div style="padding: 20px 30px; background: #f7f8f9;"><a style="font-size: 18px; font-weight: bold;" href="http://{{ domain }}{% url 'users:activate' uid64=uid token=token %}">인증하기</a></div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
{% endautoescape %}